name: Misspell Check
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
jobs:
  misspell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install misspell
        run: |
          curl -L -o ./install-misspell.sh https://raw.githubusercontent.com/client9/misspell/master/install-misspell.sh
          sh ./install-misspell.sh
      - name: Run misspell
        run: find . -type f -print0 | xargs -0 $HOME/bin/misspell -error -i transfered,derivate
